export const INITIATE_DATABASE_REQUEST = "INITIATE_DATABASE_REQUEST";
export const INITIATE_DATABASE_SUCCESS = "INITIATE_DATABASE_SUCCESS";
export const INITIATE_DATABASE_FAILURE = "INITIATE_DATABASE_FAILURE";

export const GET_ALL_TRANSACTIONS_DATA_REQUEST =
  "GET_ALL_TRANSACTIONS_DATA_REQUEST";
export const GET_ALL_TRANSACTIONS_DATA_SUCCESS =
  "GET_ALL_TRANSACTIONS_DATA_SUCCESS";
export const GET_ALL_TRANSACTIONS_DATA_FAILURE =
  "GET_ALL_TRANSACTIONS_DATA_FAILURE";


export const GET_STATISTICS_DATA_REQUEST = "GET_STATISTICS_DATA_REQUEST";
export const GET_STATISTICS_DATA_SUCCESS = "GET_STATISTICS_DATA_SUCCESS";
export const GET_STATISTICS_DATA_FAILURE = "GET_STATISTICS_DATA_FAILURE";

export const GET_BAR_CHART_DATA_REQUEST = "GET_BAR_CHART_DATA_REQUEST";
export const GET_BAR_CHART_DATA_SUCCESS = "GET_BAR_CHART_DATA_SUCCESS";
export const GET_BAR_CHART_DATA_FAILURE = "GET_BAR_CHART_DATA_FAILURE";

export const GET_PIE_CHART_DATA_REQUEST = "GET_PIE_CHART_DATA_REQUEST";
export const GET_PIE_CHART_DATA_SUCCESS = "GET_PIE_CHART_DATA_SUCCESS";
export const GET_PIE_CHART_DATA_FAILURE = "GET_PIE_CHART_DATA_FAILURE";

export const GET_COMBINED_DATA_REQUEST = "GET_COMBINED_DATA_REQUEST";
export const GET_COMBINED_DATA_SUCCESS = "GET_COMBINED_DATA_SUCCESS";
export const GET_COMBINED_DATA_FAILURE = "GET_COMBINED_DATA_FAILURE";

export const CLEAR_GLOBAL_ERROR = "CLEAR_GLOBAL_ERROR";

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
